services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ecommerce_arkx_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: db-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  # server:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   container_name: server
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./server:/app
  #     - /app/node_modules

volumes:
  postgres:
